### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by yephny** [2bllw8/anemo#1]
Would you mind adding the app to the official F-Droid repository? It'd be a great addition.

**Comment by 2bllw8** [comment]
Hi, I tried to submit the app to F-Droid, but unless I provide GitLab my credit card information to _verify my account_, they won't allow me to run the pipeline, so people at F-Droid didn't accept [my request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9630).
If you have a verified GitLab account or know anyone who does, you could try sending a new request to them so that it is accepted

**Comment by yephny** [comment]
I'm sorry to hear that. It makes no sense on Gitlab's part. It's also questionable how F-Droid indirectly requires all developers to provide a 3rd party with their credit card information.

**Comment by k3b** [comment]
fortunately anemo is available in f-droid-izzy repository https://apt.izzysoft.de/fdroid/index/apk/exe.bbllw8.anemo

**Comment by yephny** [comment]
@k3b You did not read the developer's note carefully. They refused to provide Gitlab with their own credit card information, which is why they do not have a verified Gitlab account.

**Comment by licaon-kter** [comment]
Let me try that locally

**Comment by k3b** [comment]
when i last added a mergerequests for my app https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10353 there was no need to provide a creditcard info.

**Comment by 2bllw8** [comment]
@licaon-kter thank you for helping on the GitLab side I really appreciate it! I will upload a new commit to fix the issues you mentioned soon.

@k3b I was unfortunate enough to have created an account at the time they were requesting everyone to submit their credit card infos to avoid spam (see [this article](https://about.gitlab.com/blog/2021/05/17/prevent-crypto-mining-abuse/)).

**Comment by eighthave** [comment]
we definitely do not want to require anyone to give data out that they do not want to.  You can submit merge requests using the "fdroid-anyone" account, you can find the password on our wiki https://gitlab.com/fdroid/wiki

**Comment by 2bllw8** [comment]
That is very cool @eighthave, I must I have missed that back then, my bad.
I absolutely hold no grudge against F-Droid people, you do good work. I know it is a GitLab policy implemented to avoid abuse of their systems.

In other news, thanks to @licaon-kter, the merge request has been accepted, so I guess we can consider this issue fixed. Thanks everyone!

**Comment by yephny** [comment]
Great news, looking forward to the next F-Droid repo update!
