### ISSUE TITLE
[Feature request] Add fingerprint lock

### ISSUE THREAD

**Issue by Ilithy** [2bllw8/anemo#11]
it would be very practical to be able to unlock the Anemo storage via the fingerprint reader.

*This makes locking more secure, as it does not limit Anemo storage security to password length (although both of which are stored securely in android keystores)

*This makes unlocking much easier and faster.

*This prevents password forgetting.

Thanks very much.

**Comment by 2bllw8** [comment]
It took a while, but I finally implemented this in the newest [2.6.0](https://github.com/2bllw8/anemo/releases/tag/v2.6.0) version, enjoy
