### ISSUE TITLE
Question (Not an Issue): How to add a password in anemo with auto lock?

### ISSUE THREAD

**Issue by MarkCyberSecDev93** [2bllw8/anemo#14]
How to lock and add a password it if I only have Stock AOSP System file manager (Files)?

Hope my question is clear to you. 

Thanks. 🙌

**Comment by 2bllw8** [comment]
Hi, the password can be enabled from the Configuration UI. There are 2 ways to access it: from long press on the app icon shortcuts on the home screen, or from 
`Settings > Apps > Anemo > More settings in the app` (I was told on Samsung devices the last entry has a different name and it's something like "More notification settings in the app", it will still open the Configuration UI).

I hope this helps you
