### ISSUE TITLE
[Bug] File access not revoked

### ISSUE THREAD

**Issue by Ilithy** [2bllw8/anemo#16]
### Steps to reproduce

1. Copy a keepass database file _(for example)_ into the anemo storage.

2. Access it via one of the keepass software for android
  _(test with KeepassDX using the "content provider", file link type: content://exe.bbllw8.anemo.documents/document/anemo:/Documnets/ )_.
 
4. Close Keepass, and close the Anemo storage.

5. Restart Keepass, the database stored in Anemo remains accessible and modifiable. _(storage access not allowed in the options)_ 

### Expectations

Once the Anemo storage is closed, the files are no longer accessible. (file access revoked)

### Reality

Relaunch Keepass, the files stored in Anemo remains accessible and modifiable.

### App version

2.1.1

### Android version

12 (GrapheneOS)

**Comment by 2bllw8** [comment]
Fixed with commit 9e1550a

**Comment by 2bllw8** [comment]
Tested with KeepassDX, the database is not available when locked

**Comment by Ilithy** [comment]
> Tested with KeepassDX, the database is not available when locked

Thank you for reacting so quickly and solving the problem.
