### ISSUE TITLE
How to manage Anemo storage outside of Android file manager?

### ISSUE THREAD

**Issue by soopstar** [2bllw8/anemo#2]
There's a screenshot on F-Droid that shows that you can set a password for the storage. However, I can't open the app directly, and the Android file manager doesn't seem to give any options to manage Anemo. Is there some other way to manage the storage that I missed? Could it be that this isn't implemented yet?
Specs, in case this helps:
**Android version:** One UI 3 (Android 11)
**Device:** Samsung Galaxy A71 5G
**App version:** v2.0

**Comment by soopstar** [comment]
Nevermind, found it!

**Comment by yephny** [comment]
How do you do it? @soopstar

**Comment by soopstar** [comment]
Had to use the quick settings tile to manage it

**Comment by yephny** [comment]
Thanks.
