### ISSUE TITLE
[Bug] F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [2bllw8/anemo#22]
### Steps to reproduce

The either jar file is not allowed. Can we just remove it since it's available in Maven Central?

### Expectations

Jar needs to be download from maven repos or built from source.

### Reality

There is a prebuilt jar.

### App version

2.2.0

### Android version

_

**Comment by 2bllw8** [comment]
Hi, thanks for reporting.

Where can I see the failure log?

The jar in the repo is just for building in AOSP/Lineage, when building with gradle, the dependency is downloaded from the maven central repo, [see here](https://github.com/2bllw8/anemo/blob/main/app/build.gradle#L65-L68)

**Comment by linsui** [comment]
https://monitor.f-droid.org/builds/log/exe.bbllw8.anemo/11#site-footer The log is here.

> The jar in the repo is just for building in AOSP/Lineage, when building with gradle, the dependency is downloaded from the maven central repo, [see here](https://github.com/2bllw8/anemo/blob/main/app/build.gradle#L65-L68)

Then I just remove the jar. Thanks!
