### ISSUE TITLE
[Feature request] Support all picker intents

### ISSUE THREAD

**Issue by dznsm** [2bllw8/anemo#24]
### Describe what you'd like to see added to the app

Neat little app. Great to have a private place to keep files thats instantly accessible (doesnt need an extra password) when my phone is unlocked.

Anemo doesn't appear in the list of document provider apps when some kinds of picker intents are called. Would integrate better with other apps, and be more useful,1 if it supported all these.

The directory picker intent would be particularly useful, allowing you to keep data other apps use safely in directories in Anemo. Can test intent with  - Material Files (left menu > add storage > external storage).  Alternatively set a different default save path in https://github.com/Tommy-Geenexus/exif-eraser/ so you can have photos saved straight into Anemo

Other document provider apps like Nextcloud, DAVx⁵, EDS Lite etc. all show up in all picker intents

This issue overlaps with #4

**Comment by 2bllw8** [comment]
Fixed with commits 1c16ae0 and 6c16bdc .

Tested with both ExifEraser and MaterialFiles as described in the issue.
Thanks for reporting the missing functionality!
