### ISSUE TITLE
Create Misc folder to hold other file types

### ISSUE THREAD

**Issue by licaon-kter** [2bllw8/anemo#27]
### Steps to reproduce

Try to share a ZIP/APK/TTF/random file type

### Expectations

I'm able to select anemo in the share widget

### Reality

anemo is not on the list of apps I can share **to**

### App version

2.1.0

### Android version

11

**Comment by 2bllw8** [comment]
Duplicate of #21 

The import feature will be improved for the 2.4.0 version
