### ISSUE TITLE
How to access the files?

### ISSUE THREAD

**Issue by JonatasVi** [2bllw8/anemo#3]
how does this application work, because I can't open it and with that I don't see how to use it

**Comment by soopstar** [comment]
There should be a quick settings tile that you can add. You can use that to lock and unlock the storage, and set/change the password if needed

**Comment by 2bllw8** [comment]
Hi @JonatasVi

When you install the app you can find a new section in the Files app (it was called "Download" in old android versions) called "anemo", that is the private storage where you can keep your files.
As @soopstar already suggested (thank you), there's also a quick settings tile you can use to lock and unlock your storage access.
Also, you can share files to the "anemo" app and they will be saved inside the storage so you can see them in the Files app too

**Comment by soopstar** [comment]
What I typically do is, from Material Files, hit the three dots next to a folder, tap "Open with", and select "Files" (be careful not to tap Material Files)

**Comment by 2bllw8** [comment]
The "File" app I mean is the default system files app (`com.android.documentsui`) that looks like this:

![](https://images.idgesg.net/images/article/2020/02/android-file-management-files-app-100828876-large.jpg)

**Comment by alok-debnath** [comment]
I can't even figure out how this app actually works,  there is no folder in the file manager named Anemo and Don't know how to hide files using this app, the quick setting icon seems to be working and it do work to unlock and lock the animo. But other than that I don't know how I am supposed to use this app

**Comment by k3b** [comment]
I cannot see "Anemo" on my android-10 lg phone. it has a preinstalled lg-specific filemanager. There is no android standard filemaneger "com.android.documentsui" on lg phones

**Comment by 2bllw8** [comment]
All androids have the _documentsui_ app because it's used as the standard file picker, but I guess some devices do not show the icon because they have other file apps. I am working[1] on allowing to add an optional icon to the app list that will open the hidden app.
I hope this helps everyone

[1] Commit 067666f for the initial implementation

**Comment by k3b** [comment]
I just comiled the new version

The new version has a new Anemo Starter icon. When executing it shows

       Cannot find the system files app.

Note: on my android 10 lg phone there is no  "com.android.documentsui" but there is a "com.google.android.documentsui" app in the folder /system/priv-app/GoogleDocumentsUIPrebuild/

**Comment by 2bllw8** [comment]
Ok, thank you for the information, I will try to launch "com.google.android.documentsui" too

**Comment by k3b** [comment]
Using (AppManager)[https://f-droid.org/en/packages/io.github.muntashirakon.AppManager] i found the missing "default-file-manager" :-)

In the app com.google.android.documentui there is an activity com.android.documentsui.files.FilesActivity that exactly looks like as you mentioned in 

> The "File" app I mean is the default system files app (com.android.documentsui) that looks like this that seems to work

Now I have asked "AppManager" to created a shortcut to that activity.

To bad that the lg-android-cutomisation hides this

**Comment by 2bllw8** [comment]
The new version 2.1 comes with the shortcut to open the Anemo storage from the app list, I hope this makes it easier to find and organise your files!

**Comment by alok-debnath** [comment]
> The new version 2.1 comes with the shortcut to open the Anemo storage from the app list, I hope this makes it easier to find and organise your files!

I got error "Can't find system files app". Device: Samsung

**Comment by soopstar** [comment]
Try getting to the system files app first, then opening the app shortcut. If it helps, I got there from Material Files
