### ISSUE TITLE
[feature request] Mode disable screenshots/hide application

### ISSUE THREAD

**Issue by Wjxfi** [2bllw8/anemo#35]
### Describe what you'd like to see added to the app

Mode disable screenshots/hide application. This is used in private browsers

Please, I really need this

### Additional information

Last time you closed this issue because you didn't understand me. add it to configuration, to the password input

That should make sense now

'

I created a new issue because you didn't see the comment on the previous one

'
'

it prevents a possible spyware application from recording the anemo screen

**Comment by 2bllw8** [comment]
Duplicate of #32
