### ISSUE TITLE
[Q] Which method is used to hide

### ISSUE THREAD

**Issue by jerryn70** [2bllw8/anemo#39]
Which method is used in this app to hide files ? Any encryption or second space or work profile something like that ?

**Comment by 2bllw8** [comment]
Hi, the app takes advantage of native Android features to store the files in a secure location by encrypting them with a key protected by your "lockscreen" password / code / pattern.

The Android feature that allows this is called [File-Based encryption](https://source.android.com/docs/security/features/encryption/file-based).

**Comment by jerryn70** [comment]
@2bllw8 Thanks for the information

**Comment by lgommans** [comment]
@jerryn70 note that, as mentioned in #5, anyone with access to the storage can read the files from `/data/data/exe.bbllw8.anemo/file/anemo`. The Android feature mentioned above seems to be a form of disk encryption that the OS vendor can enable, not something that Anemo uses to encrypt the files. All files on your device's internal storage are encrypted (or not) in this way, so also the ones visible in the regular file manager. The files in Anemo are not encrypted with the password that Anemo prompts for (that's what the answer above sounded like to me until I saw a reference to #5 in another ticket, hence adding this clarification).

**Comment by pixel2user** [comment]
> as mentioned in [#5](https://github.com/2bllw8/anemo/issues/5), anyone with [root as in  #5] access to the storage can read the files

@lgommans - Thanks you for pointing this out! 

I will use https://github.com/leonlatsch/Photok instead for photos/videos: "Imported media files are encrypted on the device using AES-256 and only decrypted in memory when using the app. This makes Photok different from other encrypted gallery apps."

**Comment by 2bllw8** [comment]
> [@jerryn70](https://github.com/jerryn70) note that, as mentioned in [#5](https://github.com/2bllw8/anemo/issues/5), anyone with access to the storage can read the files from `/data/data/exe.bbllw8.anemo/file/anemo`. [...] All files on your device's internal storage are encrypted (or not) in this way, so also the ones visible in the regular file manager.

That is incorrect.
The files are **NOT** available to "anyone with access to the storage".
You might be confusing the `/data/data` path with the `/sdcard/Android/data`. The latter used to be readable to anyone with access to storage up android 11, when the "scoped storage" feature was introduced.
Regardless, this app stores the files in `/data/data`, which can only be accessed by highly privileged processes, regardless of android versions.

This of course won't protect users who have mechanisms to grant "root access" to 3rd party apps on their devices, or use things like rooted adb shell, but that is just on the user who weakens the security model under which apps are supposed to operate in android.

**Comment by pixel2user** [comment]
> [@jerryn70](https://github.com/jerryn70) note that, as mentioned in [#5](https://github.com/2bllw8/anemo/issues/5), anyone with access to the storage can read the files from `/data/data/exe.bbllw8.anemo/file/anemo`. 

Does translate to "anyone with root access can see the files at /data/data/exe.bbllw8.anemo/file/anemo" https://github.com/2bllw8/anemo/issues/5#issue-1167320185

**Comment by lgommans** [comment]
> The files are **NOT** available to "anyone with access to the storage".

Sorry, I didn't say it precisely enough. I meant "the storage" as a whole, like if you desolder the storage chip and it's not encrypted or you can abuse a vulnerability, run as root, receive a malicious OS update... that sort of thing.

When read in the sense of the legacy Android storage access permission, of course you're right. An attacker indeed needs a higher access level than what apps get on any stock Android shipped with Google services can be granted. I was yesterday trying to find out if system/vendor apps can access it and it doesn't seem like it (`su`ing to uids such as 1000, "system", didn't let me enumerate files within subdirectories of `/data/data`) which positively surprised me!
