### ISSUE TITLE
Unavailable in Image mode

### ISSUE THREAD

**Issue by licaon-kter** [2bllw8/anemo#4]
self build 2f6c53a706537c02aff8822a2ab214e9171e5ef4

[Conversations](https://github.com/iNPUTmice/Conversations/) - chat - attach file - menu - Anemo present

[Conversations](https://github.com/iNPUTmice/Conversations/) - chat - attach image - menu - Anemo not available?

Anemo has a Pictures section.

**Comment by 2bllw8** [comment]
Files are not exposed to the MediaProvider of android. I'll look to see if this can be implemented in future

**Comment by licaon-kter** [comment]
Eg. SimpleGalleryPro or Userland appear both for Files and Images

**Comment by k3b** [comment]
this code from https://github.com/k3b/Zip2Saf/blob/master/app/src/main/java/de/k3b/android/zip2saf/ZipReadStorageProvider.java  will add the preview

    /**
     * Open and return a thumbnail of the requested document.
     * A provider should return a thumbnail closely matching the hinted size, attempting to
     * serve from a local cache if possible. A provider should never return images more than double
     * the hinted size.
     * If you perform expensive operations to download or generate a thumbnail, you should
     * periodically check CancellationSignal.isCanceled() to abort abandoned thumbnail requests.
     * <p>
     * See Also:
     * DocumentsContract.Document.FLAG_SUPPORTS_THUMBNAIL
     *
     * @param documentId the document to return.
     * @param sizeHint   hint of the optimal thumbnail dimensions.
     * @param signal     used by the caller to signal if the request should be cancelled. May be null.
     * @throws AuthenticationRequiredException – If authentication is required from the user (such as login credentials), but it is not guaranteed that the client will handle this properly.
     */
    @Override
    public AssetFileDescriptor openDocumentThumbnail(final String documentId, final Point sizeHint,
                                                     final CancellationSignal signal) throws FileNotFoundException {
        String dbgMsg = "openDocumentThumbnail('" + documentId + "'," + sizeHint + ") ";
        log(dbgMsg);

        if (ZipReadStorageProvider.isMissingReadPermission(getContext(), "openDocumentThumbnail")) {
            return null;
        }
        // Assume documentId points to an image file. Build a thumbnail no larger than twice the sizeHint
        BitmapFactory.Options options = new BitmapFactory.Options();
        options.inJustDecodeBounds = true;
        BitmapFactory.decodeFile(documentId, options);
        final int targetHeight = 2 * sizeHint.y;
        final int targetWidth = 2 * sizeHint.x;
        final int height = options.outHeight;
        final int width = options.outWidth;
        options.inSampleSize = 1;
        if (height > targetHeight || width > targetWidth) {
            final int halfHeight = height / 2;
            final int halfWidth = width / 2;
            // Calculate the largest inSampleSize value that is a power of 2 and keeps both
            // height and width larger than the requested height and width.
            while ((halfHeight / options.inSampleSize) > targetHeight
                    || (halfWidth / options.inSampleSize) > targetWidth) {
                options.inSampleSize *= 2;
            }
        }
        options.inJustDecodeBounds = false;
        File tempFile;
        FileOutputStream out = null;
        InputStream inputStream = null;

        try {
            inputStream = openZipEntryInputStream(documentId, dbgMsg + " create thumbnail");
            Bitmap bitmap = BitmapFactory.decodeStream(inputStream, null, options);
            tempFile = File.createTempFile("thumbnail", null, getContext().getCacheDir());
            out = new FileOutputStream(tempFile);
            bitmap.compress(Bitmap.CompressFormat.PNG, 90, out);
        } catch (IOException e) {
            Log.e(TAG, dbgMsg + "Error writing thumbnail", e);
            return null;
        } finally {
            closeSilently(inputStream, dbgMsg + "  closing thumbnail original");
            closeSilently(out, dbgMsg + " closing generated thumbnail");
        }
        // It appears the Storage Framework UI caches these results quite aggressively so there is little reason to
        // write your own caching layer beyond what you need to return a single AssetFileDescriptor
        return new AssetFileDescriptor(ParcelFileDescriptor.open(tempFile, ParcelFileDescriptor.MODE_READ_ONLY), 0,
                AssetFileDescriptor.UNKNOWN_LENGTH);
    }

----

DEFAULT_DOCUMENT_PROJECTION needs Root.COLUMN_ICON.

-----

Note: this fix may be a security risk because android caches the thumbnail even after the secure storage is unmounted so a bad actor can find the image in the thumbs cache you need a settings page where you can enable/disable this featue

**Comment by 2bllw8** [comment]
Fixed with commit 1c16ae0 , tested with Google Message (attach picture) and ExifEraser app which use the "pick image" intent

**Comment by licaon-kter** [comment]
Wow, big change. Thanks
