### ISSUE TITLE
One small issue 

### ISSUE THREAD

**Issue by Drsexo** [2bllw8/anemo#5]
Seems like a good app but the main issue is that anyone with root access can see the files at /data/data/exe.bbllw8.anemo/file/anemo 
Still good for normal users 👍

**Comment by 2bllw8** [comment]
Yes, with root no security matters anymore... There is no point in playing mouse and cat games to handle these situations, I prefer to keep the app simple and rely on the security a good OS should provide. Thanks for the appreciation!
