### ISSUE TITLE
README.md should contain more info how to build the app if there is no keystorefile.

### ISSUE THREAD

**Issue by k3b** [2bllw8/anemo#6]
My android build system has a global "local.properies" file but no entries for androidStoreFile, androidStorePassword, androidKeyAlias, androidKeyPassword delcared in https://github.com/2bllw8/anemo/blob/main/build.gradle

As a result the app cannot be build.

As a workaround i locally commented out the affected parts in global and app build.gradle.

You can reproduce the "cannot build" if you change 'local.properties' to 'keystore.properies' in global build.gradle

**Comment by 2bllw8** [comment]
Thanks for the report, I made it so that the build works even when the signing local properties are not defined.
With commit 0042ebab65d7b841478d094846e96c2c0d58af5b it's working on my machine, please let me know if it's good for you too

**Comment by k3b** [comment]
Now the build works as expected. thanks a lot
